"""Read-only month-close workflow summary for local FirstLot FIFO artifacts.

This module builds the small management-lane view Jeff described: upload lots,
upload sales, run monthly COGS, review SKU-level unit/shipping/total/average
cost, inspect failed SKUs, and use safe reopen/append/rollback guidance. It only
reads local artifact files generated by ``app.local_cli run``.
"""
from __future__ import annotations

import csv
import json
from dataclasses import asdict
from datetime import datetime
from pathlib import Path
from typing import Any

from .month_history import build_rollback_plan, load_month_history

WORKFLOW_STEPS = [
    {"step": 1, "label": "Upload purchase lots CSV", "artifact": "purchase_lots.csv", "status": "operator_supplied"},
    {"step": 2, "label": "Upload sales CSV", "artifact": "movement.csv", "status": "operator_supplied"},
    {"step": 3, "label": "Run monthly COGS", "artifact": "cogs_detail.csv", "status": "local_cli_run"},
    {"step": 4, "label": "Review SKU-level COGS", "artifact": "cogs_detail.csv", "status": "ready_when_rows_exist"},
    {"step": 5, "label": "Review failed SKU queue / fix / rerun", "artifact": "failed_sku_queue.csv", "status": "read_only_guidance"},
]

REQUIRED_ARTIFACTS = [
    "cogs_detail.csv",
    "failed_sku_queue.csv",
    "month_history.json",
    "close_packet.json",
]


def _load_rows(out_dir: str | Path, stem: str) -> list[dict[str, Any]]:
    """Load a local artifact by stem, preferring JSON and falling back to CSV."""

    out_path = Path(out_dir)
    json_path = out_path / f"{stem}.json"
    csv_path = out_path / f"{stem}.csv"
    if json_path.exists():
        with json_path.open() as handle:
            return json.load(handle)
    if csv_path.exists():
        with csv_path.open(newline="") as handle:
            return list(csv.DictReader(handle))
    return []


def _period_rows(rows: list[dict[str, Any]], period: str) -> list[dict[str, Any]]:
    return [row for row in rows if row.get("period") == period]


def _as_int(value: Any) -> int:
    return int(value or 0)


def _as_money(value: Any) -> float:
    return float(value or 0)


def _status_for_period(history_rows: list[dict[str, Any]], failed_rows: list[dict[str, Any]]) -> str:
    if failed_rows:
        return "NEEDS_FIX"
    if not history_rows:
        return "DRAFT"
    latest = history_rows[-1]
    if latest.get("status") == "APPENDED_PRIOR_MONTH":
        return "APPENDED_PRIOR_MONTH"
    if latest.get("status") == "REOPENED":
        return "REOPENED"
    return "COMPLETE"


def _month_totals(cogs_rows: list[dict[str, Any]], failed_rows: list[dict[str, Any]]) -> dict[str, Any]:
    total_units = sum(_as_int(row.get("total_quantity_sold")) for row in cogs_rows)
    total_cogs = sum(_as_money(row.get("total_cost")) for row in cogs_rows)
    failed_skus = sorted({row["sku"] for row in failed_rows})
    return {
        "sku_count": len({row["sku"] for row in cogs_rows}),
        "total_units_sold": total_units,
        "total_cogs": f"{total_cogs:.2f}",
        "failed_sku_count": len(failed_skus),
        "failed_skus": failed_skus,
        "shortfall_quantity": sum(_as_int(row.get("shortfall_quantity")) for row in failed_rows),
    }


def _sku_level_cogs(cogs_rows: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """Return the exact SKU-level cost columns needed by the management lane."""

    rows: list[dict[str, Any]] = []
    for row in sorted(cogs_rows, key=lambda item: item["sku"]):
        quantity = _as_int(row.get("total_quantity_sold"))
        merchandise_cost = _as_money(row.get("merchandise_cost"))
        unit_cost = merchandise_cost / quantity if quantity else 0.0
        rows.append(
            {
                "sku": row["sku"],
                "period": row["period"],
                "units_sold": quantity,
                "unit_cost": f"{unit_cost:.2f}",
                "shipping_cost": row.get("shipping_cost", "0.00"),
                "total_cost": row.get("total_cost", "0.00"),
                "average_cost": row.get("average_cost", "0.00"),
                "source_artifact": "cogs_detail.csv",
            }
        )
    return rows


def _management_actions(out_dir: str | Path, period: str, failed_rows: list[dict[str, Any]]) -> dict[str, Any]:
    out = str(Path(out_dir))
    actions = {
        "failed_sku_queue_command": f"python3 -m app.local_cli failed-skus --out {out} --period {period}",
        "fix_plan_command": f"python3 -m app.local_cli fix-plan --out {out} --period {period}",
        "rerun_after_fix_mode": "--reopen",
        "append_prior_month_mode": "--append-prior-month",
        "rollback": "read_only_plan_only",
        "rollback_plan_command": f"python3 -m app.local_cli rollback-plan --out {out} --period {period}",
        "live_mutations_performed": [],
    }
    if failed_rows:
        actions["next_step"] = "Fix local lots/sales CSV inputs for failed SKUs, then rerun the period with --reopen."
    else:
        actions["next_step"] = "Review close packet and month history before final local handoff."
    return actions


def build_month_close_workflow(out_dir: str | Path, *, period: str, include_rollback_plan: bool = False) -> dict[str, Any]:
    """Build a read-only workflow payload from local FIFO output artifacts."""

    out_path = Path(out_dir)
    cogs_rows = _period_rows(_load_rows(out_path, "cogs_detail"), period)
    failed_rows = _period_rows(_load_rows(out_path, "failed_sku_queue"), period)
    history_records = [asdict(record) for record in load_month_history(out_path)]
    period_history = [record for record in history_records if record["period"] == period]
    artifact_status = {name: (out_path / name).exists() for name in REQUIRED_ARTIFACTS}

    payload: dict[str, Any] = {
        "workflow_type": "firstlot_fifo_month_close_management",
        "safety_mode": "local_fixture_only_no_live_writes",
        "period": period,
        "status": _status_for_period(period_history, failed_rows),
        "workflow_steps": WORKFLOW_STEPS,
        "artifact_status": artifact_status,
        "month_totals": _month_totals(cogs_rows, failed_rows),
        "sku_level_cogs": _sku_level_cogs(cogs_rows),
        "failed_sku_queue": sorted(failed_rows, key=lambda row: row["sku"]),
        "month_history": period_history,
        "management_actions": _management_actions(out_path, period, failed_rows),
        "prohibited_scope": [
            "no live database writes",
            "no Storage Standard/client-data mutation",
            "no .env or secrets",
            "no production Amazon/Shopify calls",
            "no live rollback/migration/upload mutation scripts",
        ],
    }
    if include_rollback_plan and period_history:
        payload["rollback_plan"] = build_rollback_plan(
            out_path,
            period,
            recorded_at=datetime.fromisoformat(period_history[-1]["recorded_at"]),
            note="read-only management workflow preview",
        )
    return payload
