export const intakeModes = {
  sample: {
    key: 'sample',
    label: 'Use sample data',
    status: 'Selected now',
    tone: 'green',
    headline: 'Sample FIFO packet is ready to run',
    body: 'Checked-in purchase lots and movement CSV fixtures feed the workflow. This is the safe review path for the Friday MVP.',
    nextAction: 'Run FIFO close from local artifacts'
  },
  uploadMock: {
    key: 'uploadMock',
    label: 'Upload mock',
    status: 'Quarantined mock',
    tone: 'amber',
    headline: 'Upload lane is mocked and does not send files',
    body: 'The future upload path is represented as a local-only review state. File pickers, production APIs, and live storage writes stay disabled in autonomous mode.',
    nextAction: 'Review mappings before enabling real uploads'
  }
};

export const columnMappings = [
  {
    source: 'Purchase lots CSV',
    required: true,
    status: 'Ready',
    tone: 'green',
    matched: ['lot_id', 'sku', 'received_date', 'quantity', 'unit_cost'],
    reviewNote: 'All required lot costing fields mapped to FIFO engine inputs.'
  },
  {
    source: 'Sales/movement CSV',
    required: true,
    status: 'Ready',
    tone: 'green',
    matched: ['sale_id', 'sku', 'sale_date', 'quantity'],
    reviewNote: 'Movement rows can be consumed by sale date in deterministic order.'
  },
  {
    source: 'Landed cost inputs',
    required: false,
    status: 'Optional mock',
    tone: 'amber',
    matched: ['freight_amount', 'tariff_amount', 'duty_amount'],
    reviewNote: 'Shown as future allocation lane; not included in the current fixture calculation.'
  },
  {
    source: 'SKU mapping',
    required: false,
    status: 'Needs operator review',
    tone: 'amber',
    matched: ['source_sku', 'firstlot_sku', 'channel'],
    reviewNote: 'Mock review warns where Amazon/Shopify aliases will map into FirstLot SKUs.'
  }
];

export const exceptionGuidance = [
  {
    title: 'Resolve insufficient inventory before close',
    severity: 'Blocker',
    tone: 'red',
    action: 'Add a missing purchase lot, correct the sale quantity, or mark the movement for accounting review.',
    owner: 'Ops + bookkeeping'
  },
  {
    title: 'Confirm landed-cost policy',
    severity: 'Review',
    tone: 'amber',
    action: 'Decide whether freight, tariff, and duty should be allocated before exporting final COGS.',
    owner: 'Controller'
  },
  {
    title: 'Save export packet after exceptions are signed off',
    severity: 'Next step',
    tone: 'blue',
    action: 'Download JSON packet from this demo; CSV packet is generated by the local CLI path.',
    owner: 'Close operator'
  }
];

export const inventoryTracking = [
  {
    sku: 'SKU-A',
    onHand: 65,
    inbound: 80,
    adjustments: 0,
    valuation: 747.5,
    status: 'Healthy',
    guidance: 'Enough on-hand for current close; inbound PO extends cover.'
  },
  {
    sku: 'SKU-B',
    onHand: 10,
    inbound: 25,
    adjustments: -2,
    valuation: 127.5,
    status: 'Watch',
    guidance: 'Low remaining layer after May sales; reconcile adjustment before month-end.'
  },
  {
    sku: 'SKU-C',
    onHand: 0,
    inbound: 40,
    adjustments: 0,
    valuation: 0,
    status: 'Exception',
    guidance: 'Shortfall exists in demo run; receive inventory or correct movement.'
  }
];

export const valuationSnapshots = [
  ['Opening inventory value', '$1,930.00'],
  ['May FIFO COGS', '$1,055.00'],
  ['Ending inventory value', '$875.00'],
  ['Open exception exposure', '$90.00 estimated']
];

export const demandPlanning = [
  {
    sku: 'SKU-A',
    velocity: '18 units/week',
    leadTime: '21 days',
    reorderPoint: 54,
    stockoutRisk: 'Low',
    marginImpact: '$410 protected by inbound PO',
    recommendation: 'No emergency order; monitor next two weeks.'
  },
  {
    sku: 'SKU-B',
    velocity: '11 units/week',
    leadTime: '28 days',
    reorderPoint: 44,
    stockoutRisk: 'Medium',
    marginImpact: '$260 at risk if inbound slips',
    recommendation: 'Confirm supplier ETA and review safety stock.'
  },
  {
    sku: 'SKU-C',
    velocity: '9 units/week',
    leadTime: '35 days',
    reorderPoint: 45,
    stockoutRisk: 'High',
    marginImpact: '$540 at risk from shortfall/backorder',
    recommendation: 'Escalate replenishment or pause oversell channel.'
  }
];

export const exportPacketChecklist = [
  {
    artifact: 'COGS summary',
    format: 'CSV + JSON',
    status: 'Ready from fixture run',
    reviewer: 'Bookkeeping',
    closeUse: 'Post FIFO COGS by SKU for the May close packet.'
  },
  {
    artifact: 'Remaining layers',
    format: 'CSV + JSON',
    status: 'Ready from fixture run',
    reviewer: 'Controller',
    closeUse: 'Tie ending inventory value back to open lots and unit costs.'
  },
  {
    artifact: 'Exceptions',
    format: 'CSV + JSON',
    status: 'Requires sign-off',
    reviewer: 'Ops lead',
    closeUse: 'Document insufficient inventory before final export.'
  },
  {
    artifact: 'Sale-to-lot audit trail',
    format: 'CSV + JSON',
    status: 'Ready from fixture run',
    reviewer: 'Audit support',
    closeUse: 'Trace each sale movement to consumed FIFO lots.'
  },
  {
    artifact: 'Close notes',
    format: 'Markdown mock',
    status: 'Drafted in UI',
    reviewer: 'Close operator',
    closeUse: 'Summarize actions taken, remaining blockers, and regeneration commands.'
  }
];

export const amazonConnectorMock = {
  headline: 'Amazon connector mock: import-only, local fixture contract',
  safety: 'No Seller Central, SP-API, settlement, or order endpoint is called by this demo.',
  lanes: [
    {
      name: 'Orders / movements',
      source: 'amazon_orders_fixture.csv',
      mappedTo: 'movement.csv rows',
      status: 'Mock contract',
      guardrail: 'Read local CSV only; no production API token or .env access.'
    },
    {
      name: 'SKU aliases',
      source: 'amazon_sku_aliases_fixture.csv',
      mappedTo: 'FirstLot SKU mapping review',
      status: 'Needs operator approval',
      guardrail: 'Alias changes are staged in review and never written to live catalog data.'
    },
    {
      name: 'Returns / adjustments',
      source: 'amazon_returns_fixture.csv',
      mappedTo: 'Exception and adjustment review',
      status: 'Future fixture lane',
      guardrail: 'Returns are shown as proposed close exceptions until reviewed.'
    }
  ]
};

export const closeActionQueue = [
  {
    step: '1',
    title: 'Fix blocker exceptions',
    detail: 'Resolve SKU-C short inventory by adding a lot, correcting movement, or documenting the accounting exception.',
    tone: 'red'
  },
  {
    step: '2',
    title: 'Confirm mappings and landed-cost policy',
    detail: 'Approve required lot/movement fields and decide whether freight/tariff allocation is in scope for this close.',
    tone: 'amber'
  },
  {
    step: '3',
    title: 'Export reviewed packet',
    detail: 'Download or regenerate the local packet after exceptions and mappings are signed off.',
    tone: 'blue'
  }
];
