export const intakeModes = {
  sample: {
    key: 'sample',
    label: 'Use sample data',
    status: 'Selected now',
    tone: 'green',
    headline: 'Sample FIFO packet is ready to run',
    body: 'Checked-in purchase lots and movement CSV fixtures feed the workflow. This is the safe review path for the Friday MVP.',
    nextAction: 'Run FIFO close from local artifacts'
  },
  uploadMock: {
    key: 'uploadMock',
    label: 'Upload mock',
    status: 'Quarantined mock',
    tone: 'amber',
    headline: 'Upload lane is mocked and does not send files',
    body: 'The future upload path is represented as a local-only review state. File pickers, production APIs, and live storage writes stay disabled in autonomous mode.',
    nextAction: 'Review mappings before enabling real uploads'
  }
};

export const columnMappings = [
  {
    source: 'Purchase lots CSV',
    required: true,
    status: 'Ready',
    tone: 'green',
    matched: ['lot_id', 'sku', 'received_date', 'quantity', 'unit_cost'],
    reviewNote: 'All required lot costing fields mapped to FIFO engine inputs.'
  },
  {
    source: 'Sales/movement CSV',
    required: true,
    status: 'Ready',
    tone: 'green',
    matched: ['sale_id', 'sku', 'sale_date', 'quantity'],
    reviewNote: 'Movement rows can be consumed by sale date in deterministic order.'
  },
  {
    source: 'Landed cost inputs',
    required: false,
    status: 'Optional mock',
    tone: 'amber',
    matched: ['freight_amount', 'tariff_amount', 'duty_amount'],
    reviewNote: 'Shown as future allocation lane; not included in the current fixture calculation.'
  },
  {
    source: 'SKU mapping',
    required: false,
    status: 'Needs operator review',
    tone: 'amber',
    matched: ['source_sku', 'firstlot_sku', 'channel'],
    reviewNote: 'Mock review warns where Amazon/Shopify aliases will map into FirstLot SKUs.'
  }
];

export const mappingReviewChecklist = [
  {
    check: 'Required FIFO keys',
    status: 'Pass',
    confidence: 'High',
    detail: 'lot_id, sku, received_date, quantity, unit_cost, sale_id, sale_date, and movement quantity are present in the sample packet.'
  },
  {
    check: 'Date parse review',
    status: 'Pass',
    confidence: 'High',
    detail: 'Fixture dates use ISO format and preserve the original CSV values for future audit notes.'
  },
  {
    check: 'Landed cost allocation',
    status: 'Deferred',
    confidence: 'Needs policy',
    detail: 'Freight, tariff, and duty fields are visible as optional inputs but are not applied to the fixture COGS run.'
  },
  {
    check: 'Channel SKU aliases',
    status: 'Review',
    confidence: 'Operator approval',
    detail: 'Amazon/Shopify aliases should be approved before connector-derived movements are merged into the close run.'
  }
];

export const closeReadinessTimeline = [
  {
    stage: '1. Intake packet',
    state: 'Ready',
    tone: 'green',
    owner: 'Close operator',
    evidence: 'Checked-in purchase lot and movement fixtures are selected.'
  },
  {
    stage: '2. Mapping review',
    state: 'Review required',
    tone: 'amber',
    owner: 'Ops lead',
    evidence: 'Required columns pass; landed-cost and SKU alias policy remain explicit review gates.'
  },
  {
    stage: '3. FIFO run',
    state: 'Generated',
    tone: 'green',
    owner: 'FirstLot engine',
    evidence: 'Local artifacts are regenerated by scripts/regenerate_firstlot_demo_artifacts.py.'
  },
  {
    stage: '4. Exception sign-off',
    state: 'Blocked',
    tone: 'red',
    owner: 'Ops + bookkeeping',
    evidence: 'SKU-C insufficient inventory must be resolved or signed off before final packet approval.'
  },
  {
    stage: '5. Accounting packet',
    state: 'Draft ready',
    tone: 'blue',
    owner: 'Bookkeeping',
    evidence: 'COGS, remaining layers, shortfalls, audit trail, manifest, and notes are available as local exports.'
  }
];

export const packetCoverSheet = [
  {
    section: 'Prepared for',
    value: 'May inventory close review',
    note: 'Fixture-backed demo packet; not a production accounting export.'
  },
  {
    section: 'Prepared by',
    value: 'FirstLot local demo workflow',
    note: 'Generated from checked-in artifacts with no database writes or API calls.'
  },
  {
    section: 'Open blocker',
    value: 'SKU-C insufficient inventory',
    note: 'Resolve, correct source data, or document sign-off before final close.'
  },
  {
    section: 'Regeneration command',
    value: 'make check-firstlot-demo',
    note: 'Runs the safe local artifact and consistency checks from the repo root.'
  }
];

export const uploadMockFiles = [
  {
    fileName: 'purchase_lots_sample.csv',
    rows: 5,
    requiredColumns: '5 / 5',
    status: 'Ready for mapping',
    guidance: 'Use as the lot-cost source of truth for this local demo close.'
  },
  {
    fileName: 'movement_sample.csv',
    rows: 4,
    requiredColumns: '4 / 4',
    status: 'Ready for mapping',
    guidance: 'Movement is sorted by sale date and consumed against available lots.'
  },
  {
    fileName: 'landed_costs_optional.csv',
    rows: 0,
    requiredColumns: '0 / optional',
    status: 'Deferred',
    guidance: 'Freight, duty, and tariff allocation are visible as a future lane, not applied to fixture COGS.'
  }
];

export const exceptionGuidance = [
  {
    title: 'Resolve insufficient inventory before close',
    severity: 'Blocker',
    tone: 'red',
    action: 'Add a missing purchase lot, correct the sale quantity, or mark the movement for accounting review.',
    owner: 'Ops + bookkeeping'
  },
  {
    title: 'Confirm landed-cost policy',
    severity: 'Review',
    tone: 'amber',
    action: 'Decide whether freight, tariff, and duty should be allocated before exporting final COGS.',
    owner: 'Controller'
  },
  {
    title: 'Save export packet after exceptions are signed off',
    severity: 'Next step',
    tone: 'blue',
    action: 'Download JSON packet from this demo; CSV packet is generated by the local CLI path.',
    owner: 'Close operator'
  }
];

export const inventoryTracking = [
  {
    sku: 'SKU-A',
    onHand: 65,
    inbound: 80,
    adjustments: 0,
    valuation: 747.5,
    status: 'Healthy',
    guidance: 'Enough on-hand for current close; inbound PO extends cover.'
  },
  {
    sku: 'SKU-B',
    onHand: 10,
    inbound: 25,
    adjustments: -2,
    valuation: 127.5,
    status: 'Watch',
    guidance: 'Low remaining layer after May sales; reconcile adjustment before month-end.'
  },
  {
    sku: 'SKU-C',
    onHand: 0,
    inbound: 40,
    adjustments: 0,
    valuation: 0,
    status: 'Exception',
    guidance: 'Shortfall exists in demo run; receive inventory or correct movement.'
  }
];

export const valuationSnapshots = [
  ['Opening inventory value', '$1,930.00'],
  ['May FIFO COGS', '$1,055.00'],
  ['Ending inventory value', '$875.00'],
  ['Open exception exposure', '$90.00 estimated']
];

export const demandPlanning = [
  {
    sku: 'SKU-A',
    velocity: '18 units/week',
    leadTime: '21 days',
    reorderPoint: 54,
    stockoutRisk: 'Low',
    marginImpact: '$410 protected by inbound PO',
    recommendation: 'No emergency order; monitor next two weeks.'
  },
  {
    sku: 'SKU-B',
    velocity: '11 units/week',
    leadTime: '28 days',
    reorderPoint: 44,
    stockoutRisk: 'Medium',
    marginImpact: '$260 at risk if inbound slips',
    recommendation: 'Confirm supplier ETA and review safety stock.'
  },
  {
    sku: 'SKU-C',
    velocity: '9 units/week',
    leadTime: '35 days',
    reorderPoint: 45,
    stockoutRisk: 'High',
    marginImpact: '$540 at risk from shortfall/backorder',
    recommendation: 'Escalate replenishment or pause oversell channel.'
  }
];

export const replenishmentPlan = [
  {
    sku: 'SKU-A',
    action: 'Monitor',
    dueBy: 'After May close',
    reason: 'On-hand plus inbound keeps projected cover above reorder point.'
  },
  {
    sku: 'SKU-B',
    action: 'Confirm ETA',
    dueBy: 'This week',
    reason: 'Medium risk if the inbound PO slips past current lead-time assumption.'
  },
  {
    sku: 'SKU-C',
    action: 'Escalate replenishment',
    dueBy: 'Before close export',
    reason: 'Shortfall is already present in the fixture run and should block final packet approval.'
  }
];

export const exportPacketChecklist = [
  {
    artifact: 'COGS summary',
    format: 'CSV + JSON',
    status: 'Ready from fixture run',
    reviewer: 'Bookkeeping',
    closeUse: 'Post FIFO COGS by SKU for the May close packet.'
  },
  {
    artifact: 'Remaining layers',
    format: 'CSV + JSON',
    status: 'Ready from fixture run',
    reviewer: 'Controller',
    closeUse: 'Tie ending inventory value back to open lots and unit costs.'
  },
  {
    artifact: 'Exceptions',
    format: 'CSV + JSON',
    status: 'Requires sign-off',
    reviewer: 'Ops lead',
    closeUse: 'Document insufficient inventory before final export.'
  },
  {
    artifact: 'Sale-to-lot audit trail',
    format: 'CSV + JSON',
    status: 'Ready from fixture run',
    reviewer: 'Audit support',
    closeUse: 'Trace each sale movement to consumed FIFO lots.'
  },
  {
    artifact: 'Close notes',
    format: 'Markdown mock',
    status: 'Drafted in UI',
    reviewer: 'Close operator',
    closeUse: 'Summarize actions taken, remaining blockers, and regeneration commands.'
  }
];

export const exportPacketManifest = [
  {
    fileName: 'cogs_summary.csv',
    records: 2,
    owner: 'Bookkeeping',
    gate: 'Ready',
    note: 'Post SKU-level FIFO COGS after exception sign-off.'
  },
  {
    fileName: 'remaining_layers.csv',
    records: 2,
    owner: 'Controller',
    gate: 'Ready',
    note: 'Tie ending inventory valuation back to open lot layers.'
  },
  {
    fileName: 'shortfalls.csv',
    records: 1,
    owner: 'Ops lead',
    gate: 'Blocked until reviewed',
    note: 'SKU-C insufficient inventory must be resolved or signed off before final close.'
  },
  {
    fileName: 'audit_trail.csv',
    records: 4,
    owner: 'Audit support',
    gate: 'Ready',
    note: 'Sale-to-lot attribution for every allocated movement row.'
  }
];

export const amazonConnectorMock = {
  headline: 'Amazon connector mock: import-only, local fixture contract',
  safety: 'No Seller Central, SP-API, settlement, or order endpoint is called by this demo.',
  lanes: [
    {
      name: 'Orders / movements',
      source: 'amazon_orders_fixture.csv',
      mappedTo: 'movement.csv rows',
      status: 'Mock contract',
      guardrail: 'Read local CSV only; no production API token or .env access.'
    },
    {
      name: 'SKU aliases',
      source: 'amazon_sku_aliases_fixture.csv',
      mappedTo: 'FirstLot SKU mapping review',
      status: 'Needs operator approval',
      guardrail: 'Alias changes are staged in review and never written to live catalog data.'
    },
    {
      name: 'Returns / adjustments',
      source: 'amazon_returns_fixture.csv',
      mappedTo: 'Exception and adjustment review',
      status: 'Future fixture lane',
      guardrail: 'Returns are shown as proposed close exceptions until reviewed.'
    }
  ]
};

export const closeActionQueue = [
  {
    step: '1',
    title: 'Fix blocker exceptions',
    detail: 'Resolve SKU-C short inventory by adding a lot, correcting movement, or documenting the accounting exception.',
    tone: 'red'
  },
  {
    step: '2',
    title: 'Confirm mappings and landed-cost policy',
    detail: 'Approve required lot/movement fields and decide whether freight/tariff allocation is in scope for this close.',
    tone: 'amber'
  },
  {
    step: '3',
    title: 'Export reviewed packet',
    detail: 'Download or regenerate the local packet after exceptions and mappings are signed off.',
    tone: 'blue'
  }
];
